# Form implementation generated from reading ui file 'c:\Repositories\video-speller\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 700)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.subtitleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.subtitleLabel.setStyleSheet("color: gray;")
        self.subtitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.subtitleLabel.setObjectName("subtitleLabel")
        self.verticalLayout.addWidget(self.subtitleLabel)
        self.fileLayout = QtWidgets.QHBoxLayout()
        self.fileLayout.setObjectName("fileLayout")
        self.fileLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.fileLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.fileLabel.setObjectName("fileLabel")
        self.fileLayout.addWidget(self.fileLabel)
        self.fileInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.fileInput.setObjectName("fileInput")
        self.fileLayout.addWidget(self.fileInput)
        self.browseButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.browseButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.browseButton.setObjectName("browseButton")
        self.fileLayout.addWidget(self.browseButton)
        self.verticalLayout.addLayout(self.fileLayout)
        self.outputLayout = QtWidgets.QHBoxLayout()
        self.outputLayout.setObjectName("outputLayout")
        self.outputLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.outputLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.outputLabel.setObjectName("outputLabel")
        self.outputLayout.addWidget(self.outputLabel)
        self.outputDirInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.outputDirInput.setObjectName("outputDirInput")
        self.outputLayout.addWidget(self.outputDirInput)
        self.browseOutputButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.browseOutputButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.browseOutputButton.setObjectName("browseOutputButton")
        self.outputLayout.addWidget(self.browseOutputButton)
        self.verticalLayout.addLayout(self.outputLayout)
        self.timeLayout = QtWidgets.QHBoxLayout()
        self.timeLayout.setObjectName("timeLayout")
        self.intervalLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.intervalLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.intervalLabel.setObjectName("intervalLabel")
        self.timeLayout.addWidget(self.intervalLabel)
        self.intervalInput = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.intervalInput.setMaximumSize(QtCore.QSize(60, 16777215))
        self.intervalInput.setMinimum(1)
        self.intervalInput.setMaximum(60)
        self.intervalInput.setProperty("value", 2)
        self.intervalInput.setObjectName("intervalInput")
        self.timeLayout.addWidget(self.intervalInput)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.timeLayout.addItem(spacerItem)
        self.startLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.startLabel.setObjectName("startLabel")
        self.timeLayout.addWidget(self.startLabel)
        self.startTimeInput = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.startTimeInput.setEnabled(False)
        self.startTimeInput.setMinimumSize(QtCore.QSize(100, 25))
        self.startTimeInput.setMaximumSize(QtCore.QSize(100, 16777215))
        self.startTimeInput.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.startTimeInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.startTimeInput.setCurrentSection(QtWidgets.QDateTimeEdit.Section.SecondSection)
        self.startTimeInput.setTime(QtCore.QTime(0, 0, 0))
        self.startTimeInput.setObjectName("startTimeInput")
        self.timeLayout.addWidget(self.startTimeInput)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.timeLayout.addItem(spacerItem1)
        self.endLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.endLabel.setObjectName("endLabel")
        self.timeLayout.addWidget(self.endLabel)
        self.endTimeInput = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.endTimeInput.setEnabled(False)
        self.endTimeInput.setMinimumSize(QtCore.QSize(100, 25))
        self.endTimeInput.setMaximumSize(QtCore.QSize(100, 16777215))
        self.endTimeInput.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.endTimeInput.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.endTimeInput.setCurrentSection(QtWidgets.QDateTimeEdit.Section.SecondSection)
        self.endTimeInput.setTime(QtCore.QTime(0, 0, 0))
        self.endTimeInput.setObjectName("endTimeInput")
        self.timeLayout.addWidget(self.endTimeInput)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.timeLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.timeLayout)
        self.startButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.startButton.setMinimumSize(QtCore.QSize(0, 40))
        self.startButton.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #cccccc;\n"
"}")
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 1px solid #444;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"    background-color: #f0f0f0;\n"
"    color: #000000;\n"
"    height: 25px;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #4CAF50;\n"
"    border-radius: 4px;\n"
"}")
        self.progressBar.setMinimum(0)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.bottomLayout = QtWidgets.QHBoxLayout()
        self.bottomLayout.setSpacing(10)
        self.bottomLayout.setObjectName("bottomLayout")
        self.logLayout = QtWidgets.QVBoxLayout()
        self.logLayout.setObjectName("logLayout")
        self.logLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.logLabel.setObjectName("logLabel")
        self.logLayout.addWidget(self.logLabel)
        self.logOutput = QtWidgets.QTextEdit(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.logOutput.setFont(font)
        self.logOutput.setStyleSheet("QTextEdit {\n"
"    background-color: #2b2b2b;\n"
"    color: #f0f0f0;\n"
"    border: 1px solid #444;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"}")
        self.logOutput.setReadOnly(True)
        self.logOutput.setObjectName("logOutput")
        self.logLayout.addWidget(self.logOutput)
        self.logLayout.setStretch(1, 1)
        self.bottomLayout.addLayout(self.logLayout)
        self.previewLayout = QtWidgets.QVBoxLayout()
        self.previewLayout.setObjectName("previewLayout")
        self.previewLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.previewLabel.setObjectName("previewLabel")
        self.previewLayout.addWidget(self.previewLabel)
        self.framePreview = QtWidgets.QLabel(parent=self.centralwidget)
        self.framePreview.setMinimumSize(QtCore.QSize(320, 240))
        self.framePreview.setMaximumSize(QtCore.QSize(480, 360))
        self.framePreview.setStyleSheet("QLabel {\n"
"    background-color: #1a1a1a;\n"
"    border: 1px solid #444;\n"
"    border-radius: 5px;\n"
"}")
        self.framePreview.setScaledContents(False)
        self.framePreview.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.framePreview.setObjectName("framePreview")
        self.previewLayout.addWidget(self.framePreview)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.previewLayout.addItem(spacerItem3)
        self.bottomLayout.addLayout(self.previewLayout)
        self.verticalLayout.addLayout(self.bottomLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpenDictionary = QtGui.QAction(parent=MainWindow)
        self.actionOpenDictionary.setObjectName("actionOpenDictionary")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionOpenDictionary)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.fileInput, self.browseButton)
        MainWindow.setTabOrder(self.browseButton, self.intervalInput)
        MainWindow.setTabOrder(self.intervalInput, self.startTimeInput)
        MainWindow.setTabOrder(self.startTimeInput, self.endTimeInput)
        MainWindow.setTabOrder(self.endTimeInput, self.startButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Video Spell Checker"))
        self.titleLabel.setText(_translate("MainWindow", "Video Spell Checker"))
        self.subtitleLabel.setText(_translate("MainWindow", "Проверка орфографии в видео (русский/английский)"))
        self.fileLabel.setText(_translate("MainWindow", "Видео файл:"))
        self.fileInput.setPlaceholderText(_translate("MainWindow", "Выберите видео файл..."))
        self.browseButton.setText(_translate("MainWindow", "Обзор..."))
        self.outputLabel.setText(_translate("MainWindow", "Папка вывода:"))
        self.outputDirInput.setPlaceholderText(_translate("MainWindow", "Папка для результатов..."))
        self.browseOutputButton.setText(_translate("MainWindow", "Обзор..."))
        self.intervalLabel.setText(_translate("MainWindow", "Интервал (сек):"))
        self.startLabel.setText(_translate("MainWindow", "Начало [час:мин:сек]:"))
        self.startTimeInput.setDisplayFormat(_translate("MainWindow", "HH:mm:ss"))
        self.endLabel.setText(_translate("MainWindow", "Конец [час:мин:сек]:"))
        self.endTimeInput.setDisplayFormat(_translate("MainWindow", "HH:mm:ss"))
        self.startButton.setText(_translate("MainWindow", "Начать проверку"))
        self.progressBar.setFormat(_translate("MainWindow", "%p% - Обработано кадров"))
        self.logLabel.setText(_translate("MainWindow", "Лог обработки:"))
        self.previewLabel.setText(_translate("MainWindow", "Текущий кадр:"))
        self.framePreview.setText(_translate("MainWindow", "Ожидание обработки..."))
        self.menuFile.setTitle(_translate("MainWindow", "Файл"))
        self.menuHelp.setTitle(_translate("MainWindow", "Помощь"))
        self.actionOpenDictionary.setText(_translate("MainWindow", "Открыть пользовательский словарь..."))
        self.actionExit.setText(_translate("MainWindow", "Выход"))
        self.actionAbout.setText(_translate("MainWindow", "О программе..."))
